name: logosophy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

version: 0.4.1+33

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flex_color_scheme: ^8.3.0
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.1
  go_router: ^16.2.0
  logging: ^1.3.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  path_provider: ^2.1.5
  path: ^1.9.1
  country_flags: ^4.0.1
  riverpod_annotation: ^3.0.1
  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  scrollable_positioned_list: ^0.3.8
  intl: ^0.20.2
  firebase_crashlytics: ^5.0.2
  supabase_flutter: ^2.10.3
  http: ^1.5.0
  pdfrx: ^2.2.18
  archive: ^4.0.7
  firebase_core: ^4.3.0
  dio: ^5.9.0
  hive_ce_flutter: ^2.3.4
  hive_ce: ^2.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.1
  freezed: ^3.0.6
  slang_build_runner: ^4.8.0
  build_runner: ^2.5.4
  riverpod_lint: ^3.0.1
  lints: ^6.0.0
  custom_lint: ^0.8.0
  hive_ce_generator: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - .env
